spring:
  application:
    name: zezari-prototype
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
file:
  upload-dir: /Users/jiyoo/software/projects/zezari-prototype/images/